# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '855b26f2-4d50-4b33-8f22-6fc85a836d87'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'MyLab'
    location: 'East Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/harvinchou/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json?token=AB6NNTFW5EXRRCRC52ZHP6TAY6QE2'
    overrideParameters: '-projectName myarmpipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'